### ISSUE TITLE
send_money endpoint now requires data to be wrapped in a "transaction"

### ISSUE THREAD

**Issue by nrjudson** [coinbase/coinbase-bitmonet-sdk#10]
In the file CoinbasePaymentProcessor.java, constructJSONForSendMoney(final String item, final double amount) creates the json that will be submitted to the send_money endpoint of Coinbase.

This worked for me until Friday, and then I realized we were getting 404s back from Coinbase with this message: {"success":false,"errors":["Required parameter missing: transaction"]}

Looking at their documentation, it seems they've made it required to include a "transaction" object in this json.  A quick fix would be to wrap what's currently provided in constructJSONForSendMoney in a "transaction", and then send that json.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
