### ISSUE TITLE
Callback handling is totally wrong

### ISSUE THREAD

**Issue by torinnguyen** [coinbase/coinbase-bitmonet-sdk#6]
According to API docs, I set the redirect uri to be "urn:ietf:wg:oauth:2.0:oob"
The callback is having this format https://coinbase.com/oauth/authorize/ACCESS_TOKEN_HERE

While the current source code is looking for "?code=" pattern.

I have modified my own code to work with the newer format, but unsure if I should keep the old format for backward compatibility?

**Comment by souravmind** [comment]
Let me know what should i used for callback url

**Comment by souravmind** [comment]
I am unable to come back to my application after authenticate.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
