### ISSUE TITLE
When user has already been authorized, walletOAuthStatusListener(boolean status) is not being called

### ISSUE THREAD

**Issue by torinnguyen** [coinbase/coinbase-bitmonet-sdk#7]
When user has already been authorized, calling Bitmonet.requestWalletAuthorization(this); simply show a Toast message.

It would be nicer and cleaner to have the interface walletOAuthStatusListener(true); to be triggered, so that the code flow is the same for both logged in & non-logged in cases.

**Comment by drewrothstein** [comment]
Hi, we are closing out PRs + Issues as this project is being archived.
